### ISSUE TITLE
convert ol-util to typescript

### ISSUE THREAD

**Issue by LukasLohoff** [terrestris/ol-util#712]
Current state: ol-util supports js-doc types which can be checked via typecheck. There were already several improvements by @simonseyock:

- https://github.com/terrestris/ol-util/pull/635
- https://github.com/terrestris/ol-util/pull/631
- https://github.com/terrestris/ol-util/pull/630
- https://github.com/terrestris/ol-util/pull/624

Do you think ol-utli could be migrated to typescript entirely?

In my opinion, full typescript support will make writing and importing types easier when working with other typescript projects.

**Comment by simonseyock** [comment]
sure that is absolutely possible. It just some work. I don't think there exist automated tools. But due to the jsdoc typechecking there are already some prerequisites fulfilled. There is already a tsconfig and we use typedoc.
We would need to add a transpiling via babel or tsc and rewrite all the code.
